-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 17:56:33 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema amazon_webshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema amazon_webshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amazon_webshop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `amazon_webshop` ;

-- -----------------------------------------------------
-- Table `amazon_webshop`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`account` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NULL DEFAULT NULL,
  `lastname` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(25) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `is_active` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `amazon_webshop`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`address` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `door_number` VARCHAR(20) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `postal_code` VARCHAR(20) NULL DEFAULT NULL,
  `country` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `account_id` (`account_id` ASC) VISIBLE,
  CONSTRAINT `address_ibfk_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `amazon_webshop`.`account` (`account_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `amazon_webshop`.`shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`shopping_cart` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`shopping_cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_id`),
  INDEX `account_id` (`account_id` ASC) VISIBLE,
  CONSTRAINT `shopping_cart_ibfk_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `amazon_webshop`.`account` (`account_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `amazon_webshop`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`category` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `amazon_webshop`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`product` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `amazon_webshop`.`category` (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `amazon_webshop`.`cart_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`cart_item` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`cart_item` (
  `cart_item_id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`cart_item_id`),
  INDEX `cart_id` (`cart_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `cart_item_ibfk_1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `amazon_webshop`.`shopping_cart` (`cart_id`),
  CONSTRAINT `cart_item_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `amazon_webshop`.`product` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `amazon_webshop`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`inventory` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`inventory` (
  `inventory_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `stock_quantity` INT NULL DEFAULT NULL,
  `warehouse_location` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`inventory_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `inventory_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `amazon_webshop`.`product` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `amazon_webshop`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`orders` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL DEFAULT NULL,
  `address_id` INT NULL DEFAULT NULL,
  `order_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `total_price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `account_id` (`account_id` ASC) VISIBLE,
  INDEX `address_id` (`address_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `amazon_webshop`.`account` (`account_id`),
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`address_id`)
    REFERENCES `amazon_webshop`.`address` (`address_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `amazon_webshop`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`order_item` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`order_item` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_item_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `amazon_webshop`.`orders` (`order_id`),
  CONSTRAINT `order_item_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `amazon_webshop`.`product` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `amazon_webshop`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`payment` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NULL DEFAULT NULL,
  `payment_method` VARCHAR(50) NULL DEFAULT NULL,
  `payment_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `amazon_webshop`.`orders` (`order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `amazon_webshop`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon_webshop`.`review` ;

CREATE TABLE IF NOT EXISTS `amazon_webshop`.`review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `account_id` INT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `review_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`review_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `account_id` (`account_id` ASC) VISIBLE,
  CONSTRAINT `review_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `amazon_webshop`.`product` (`product_id`),
  CONSTRAINT `review_ibfk_2`
    FOREIGN KEY (`account_id`)
    REFERENCES `amazon_webshop`.`account` (`account_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
